import fs from 'node:fs'
import path from 'node:path'
import { walkContracts, readAbi, type ContractNode } from './abi'
import type { Abi, AbiFragment } from './fetch'

// Emits named tuple elements per ABI input — this is the reason we don't rely
// on viem/abitype, which produces unnamed tuples (microsoft/TypeScript#44939).
export function generateAllowTypes(
  abisDir: string,
  contractsConfig: Record<string, any>
): string {
  type Tree = Map<string, Tree | { node: ContractNode; abi: Abi }>

  const root: Tree = new Map()
  for (const node of walkContracts(contractsConfig)) {
    const abi = readAbi(abisDir, node)
    if (!abi) continue
    insertIntoTree(root, [node.chain, ...node.segments], { node, abi })
  }

  const out: string[] = []
  out.push('// AUTO-GENERATED by `zodiac pull-contracts`. Do not edit.')
  out.push('/* eslint-disable */')
  out.push('')
  out.push(
    `import type { Scoping, Options, EVERYTHING, FunctionPermission, TargetPermission } from "@zodiaceco/sdk/allow";`
  )
  out.push('')
  out.push('declare global {')
  out.push('  interface AllowKit ' + renderTree(root, '  '))
  out.push('}')
  out.push('')
  out.push('export {};')
  out.push('')
  return out.join('\n')
}

function insertIntoTree(
  tree: Map<string, any>,
  segments: string[],
  leaf: { node: ContractNode; abi: Abi }
): void {
  const [first, ...rest] = segments
  if (!first) throw new Error('empty segments')
  if (rest.length === 0) {
    tree.set(first, leaf)
    return
  }
  let child = tree.get(first)
  if (!child || child.node) {
    child = new Map()
    tree.set(first, child)
  }
  insertIntoTree(child, rest, leaf)
}

function renderTree(tree: Map<string, any>, indent: string): string {
  const lines: string[] = ['{']
  for (const [key, value] of tree) {
    const safeKey = renderPropKey(key)
    if (value instanceof Map) {
      lines.push(`${indent}  ${safeKey}: ${renderTree(value, indent + '  ')};`)
    } else {
      const { node, abi } = value as { node: ContractNode; abi: Abi }
      lines.push(
        `${indent}  ${safeKey}: ${renderContractType(node, abi, indent + '  ')};`
      )
    }
  }
  lines.push(`${indent}}`)
  return lines.join('\n')
}

function renderPropKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function renderContractType(
  node: ContractNode,
  abi: Abi,
  indent: string
): string {
  const members: string[] = []
  members.push(
    `${indent}  [EVERYTHING]: (options?: Options) => TargetPermission;`
  )

  // Members mirror what the runtime proxy can resolve, which is whatever
  // `Interface.getFunction` accepts. A name it would find ambiguous is not a
  // member there — the proxy returns undefined for it — so an overloaded name
  // is emitted once per full signature and never bare. Declaring the bare name
  // anyway is what used to make `allow.eth.susds.deposit(…)` type-check and
  // then fail at runtime.
  for (const overloads of groupByName(abi).values()) {
    const overloaded = overloads.length > 1
    for (const fragment of overloads) {
      const key = overloaded
        ? signatureFor(fragment)
        : (fragment.name as string)
      members.push(renderFunctionSignature(fragment, key, indent + '  '))
    }
  }
  return ['{', ...members, `${indent}}`].join('\n')
}

/**
 * Permissionable fragments grouped by function name, in ABI order. Two
 * fragments that render the same signature are the same function listed twice,
 * so they collapse — emitting the key twice would not compile.
 */
function groupByName(abi: Abi): Map<string, AbiFragment[]> {
  const byName = new Map<string, AbiFragment[]>()
  for (const fragment of abi) {
    if (fragment.type !== 'function') continue
    if (
      fragment.stateMutability === 'view' ||
      fragment.stateMutability === 'pure'
    ) {
      continue
    }
    const name = fragment.name as string
    if (!name) continue
    const overloads = byName.get(name) ?? []
    if (overloads.some((f) => signatureFor(f) === signatureFor(fragment))) {
      continue
    }
    byName.set(name, [...overloads, fragment])
  }
  return byName
}

/** The canonical `name(type,…)` form, which is how `Interface.getFunction`
 * addresses one overload of a name. */
function signatureFor(fragment: AbiFragment): string {
  const inputs = (fragment.inputs as AbiFragment[]) ?? []
  return `${fragment.name}(${inputs.map(canonicalTypeFor).join(',')})`
}

function canonicalTypeFor(fragment: AbiFragment): string {
  const type = fragment.type as string

  const arrayMatch = /^(.*)\[(\d*)\]$/.exec(type)
  if (arrayMatch) {
    const inner: AbiFragment = { ...fragment, type: arrayMatch[1] }
    return `${canonicalTypeFor(inner)}[${arrayMatch[2]}]`
  }

  if (type === 'tuple') {
    const components = (fragment.components as AbiFragment[]) ?? []
    return `(${components.map(canonicalTypeFor).join(',')})`
  }

  return type
}

function renderFunctionSignature(
  fragment: AbiFragment,
  key: string,
  indent: string
): string {
  const name = renderPropKey(key)
  const params: string[] = []
  for (const input of (fragment.inputs as AbiFragment[]) ?? []) {
    const paramName = sanitizeParamName(
      input.name || `arg${params.length}`,
      params.length
    )
    params.push(`${paramName}?: Scoping<${tsTypeFor(input)}>`)
  }
  params.push(`options?: Options`)
  return `${indent}${name}: (${params.join(', ')}) => FunctionPermission;`
}

function sanitizeParamName(name: string, index: number): string {
  const cleaned = name.replace(/[^A-Za-z0-9_$]/g, '_')
  if (!cleaned || /^[0-9]/.test(cleaned)) return `arg${index}`
  // Named tuple element labels can't collide with TS reserved words.
  const reserved = new Set([
    'function',
    'class',
    'new',
    'number',
    'string',
    'object',
    'boolean',
    'symbol',
    'default',
    'return',
    'this',
    'void',
    'delete',
    'in',
    'of',
    'for',
    'while',
    'switch',
    'case',
    'if',
    'else',
    'null',
    'true',
    'false',
    'undefined',
    'any',
    'never',
    'unknown',
  ])
  return reserved.has(cleaned) ? `_${cleaned}` : cleaned
}

function tsTypeFor(fragment: AbiFragment): string {
  const type = fragment.type as string

  const arrayMatch = /^(.*)\[(\d*)\]$/.exec(type)
  if (arrayMatch) {
    const inner: AbiFragment = { ...fragment, type: arrayMatch[1] }
    return `readonly (${tsTypeFor(inner)})[]`
  }

  if (type === 'tuple') {
    const components = (fragment.components as AbiFragment[]) ?? []
    if (components.length === 0) return 'Record<string, unknown>'
    const fields = components.map((c, i) => {
      const key = sanitizeParamName(c.name || `f${i}`, i)
      return `${renderPropKey(key)}: ${tsTypeFor(c)}`
    })
    return `{ ${fields.join('; ')} }`
  }

  if (type === 'address') return '`0x${string}`'
  if (type === 'bool') return 'boolean'
  if (type === 'string') return 'string'
  if (type === 'bytes') return 'import("ethers").BytesLike'
  if (/^bytes\d+$/.test(type)) return '`0x${string}`'
  if (/^u?int\d*$/.test(type)) return 'import("ethers").BigNumberish'
  return 'unknown'
}

export function writeGenerated(outFile: string, source: string): void {
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, source, 'utf8')
}
